#################################################################################################################################
# release-template.yml
# Created on 03/27/2025
#
# Copyright (C) 2025 Mehmet Bertan Tarakcioglu, Under the MIT License
#
# This file was originally created as part of the WatchDuck project CI Pipeline.
#################################################################################################################################

# Recommended usage of the reusable release workflow provided by BertantT/Swift-Executable-CI.

name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: "New release tag to create (e.g. 0.4.2)"
      release_title:
        type: string
        required: false
        default: ""
        description: "Release name for GitHub. Defaults to the new tag."
      make_latest:
        type: boolean
        required: true
        default: true
        description: "Make this release the latest."
      prerelease:
        type: boolean
        required: true
        default: false
        description: "Mark this release as a pre-release."
      run_swiftlint:
        type: boolean
        required: true
        default: true
        description: "Run SwiftLint before building. Overridden if repo variable is false."
      update_changelog:
        type: boolean
        required: true
        default: true
        description: "Auto-prepare release notes and update the changelog. Overridden if repo variable is false."

jobs:
  call-release:
    uses: BertanT/Swift-Executable-CI/.github/workflows/release.yml@ebe8abd9a650c65541bf5893509594c047f74584
    with:
      version: ${{ inputs.version }}
      exec_name: ${{ vars.EXEC_NAME }}
      swift_toolchain_version: ${{ vars.SWIFT_TOOLCHAIN_VERSION }}
      linux_sdk_url: ${{ vars.LINUX_SDK_URL }}
      linux_sdk_checksum: ${{ vars.LINUX_SDK_CHECKSUM }}
      release_title: ${{ inputs.release_title }}
      make_latest: ${{ inputs.make_latest }}
      prerelease: ${{ inputs.prerelease }}
      run_swiftlint: ${{ vars.RELEASE_RUN_SWIFTLINT != 'false' && (github.event_name != 'workflow_dispatch' || inputs.run_swiftlint) }}
      update_changelog: ${{ vars.UPDATE_CHANGELOG != 'false' && (github.event_name != 'workflow_dispatch' || inputs.update_changelog) }}