#################################################################################################################################
# build.yml
# Created on 03/27/2025
#
# Copyright (C) 2025 Mehmet Bertan Tarakcioglu, Under the MIT License
#
# This file was originally created as part of the WatchDuck project CI Pipeline.
#################################################################################################################################

# Part of the SwiftPM-Cross-Comp-CI pipeline.

# This workflow is used to only  build your Swift Executable for macOS and Linux for testing.
# It is recommended to run this on pushes to main!

name: Build

on:
  workflow_call:
    inputs:
      swift_toolchain_version:
        type: string
        required: true
        description: "Swift toolchain version. Should have the same Swift version as the static Linux SDK."
      linux_sdk_url:
        type: string
        required: true
        description: "Tarball URL link for the static Linux SDK. This should be the same Swift version as the toolchain version."
      linux_sdk_checksum:
        type: string
        required: true
        description: "Tarball Checksum for the static Linux SDK."
      run-swiftlint:
        type: boolean
        required: false
        default: false
        description: "If true, the workflow will run SwiftLint before building. Make sure you have the SwiftLint command tool plugin installed!"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-latest
    permissions:
      contents: write 
    env:
      REPO_URL: ${{ github.server_url }}/${{ github.repository }}
      TARGET_BRANCH: ${{ github.ref_name }}
      SWIFT_TOOLCHAIN_VERSION: ${{ inputs.swift_toolchain_version }}
      LINUX_SDK_URL: ${{ inputs.linux_sdk_url }}
      LINUX_SDK_CHECKSUM: ${{ inputs.linux_sdk_checksum }}
    steps:
      - name: Cloning repository.
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0
      - name: Fetch script dependencies.
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          repository: BertanT/SwiftPM-Cross-Comp-CI
          ref: main
          path: ci-scripts-${{ github.run_id }}
          sparse-checkout: '*.sh'
          sparse-checkout-cone-mode: false

      - name: Validating repository variables.
        run: ci-scripts-${{ github.run_id }}/validate-inputs-build.sh

      - name: Setting up Swift Toolchain Version ${{ env.SWIFT_TOOLCHAIN_VERSION }}.
        run: ci-scripts-${{ github.run_id }}/setup-swift.sh

      - name: Linting code with SwiftLint.
        if: ${{ inputs.run-swiftlint }}
        run: swift package plugin --allow-writing-to-package-directory swiftlint lint --progress

      - name: Installing the static Swift SDK for Linux.
        run: swift sdk install $LINUX_SDK_URL --checksum $LINUX_SDK_CHECKSUM
  
      - name: Building for debug on macOS ARM64.
        run: swift build --configuration debug --arch arm64

      - name: Building for debug on macOS x86_64.
        run: swift build --configuration debug --arch x86_64

      - name: Building for debug on Linux ARM64.
        run: swift build --configuration debug --swift-sdk aarch64-swift-linux-musl

      - name: Building for debug on Linux x86_64.
        run: swift build --configuration debug --swift-sdk x86_64-swift-linux-musl
